### ISSUE TITLE
How to speed up training ?

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#102]
Hi,

I am used to autoregressive models like VITS where to speed up training the batch size can be increased. You know when the batch size is too high when all GPU VRAM is used (for eg with an RTX 3090 24GB with a sample length of max 9 seconds 40 is the max batch size).

Yet with Portaspeech I can increase the batch size without any effect on the "iterations / s" shown during training. Only the VRAM usage is increased (but not that much compared to VITS).

So I don't understand how to maximize my Graphics Card usage. I've just noticed GPU power consumption is much environmental friendlier than VITS (around half the power consumption of VITS) but I don't know if it is well used or if it could be better used.

Any directions appreciated!

**Comment by Flux9665** [comment]
Increasing the batchsize usually leads to more stable training and can also lead to quicker convergence. Everything is pretty efficient, so the batchsize can be scaled up quite high before a drop in speed is noticeable. Too high batchsizes are however known to cause problems with generative models. So I think anything in the range of 16 to 128 is fine, I personally like to use 32 on 48GB VRAM GPUs.

A major difference is that VITS predicts the wave, which is tens of thousands of samples per second, whereas PortaSpeech predicts only spectrogram frames, which is more in the hundreds. Splitting the TTS task into the two sub-steps of going to spectrogram first and then to wave is generally more power, compute and data efficient.

**Comment by Ca-ressemble-a-du-fake** [comment]
Ok got it thank you.
