### ISSUE TITLE
Audio enhancements for podcast do not produce any sound

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#103]
Hi,

While reading the code I stumble across an interesting feature namely `use_signalprocessing` disabled by default. 

So I tried to generate samples with read text to file reader initializing portaspeechinterface with use_signalprocessing = True and everything was cut off. So only clicks separating the sentences could be heard.

I tried with Meta model and one that I finetuned with similar results.

Is it supposed to work already or is it supposed to be tweaked before usage ? If so what should be tweaked? 

Thanks in advance for you help,

**Comment by Flux9665** [comment]
The things that are applied to the output signal are very dependent on the voice that is used. I tried this as an experiment, but I think I will remove it again in a future release. I believe it is better to handle these things outside of the TTS as a secondary step. In my tests it worked well for a loud male voice with a fundamental frequency of around 90Hz. I haven't tried it in a while, but I'm not aware of anything that would break compatibility. I will test later, but as I mentioned, probably remove in a future release.

**Comment by Ca-ressemble-a-du-fake** [comment]
Meta French model has a female voice, so I will try and find its fundamental frequency and tweak some frequencies (offset the cut off frequencies). Just to hear what this post processing can bring.

**Comment by Ca-ressemble-a-du-fake** [comment]
FYI What cuts off everything is the lowpass filtering `LowpassFilter(cutoff_frequency_hz=17000)`. The Meta voice has a fundamental frequency of 219 Hz and all the spectre content is below 12 kHz . So cutting off below 17kHz should not be a problem. Applying the same LP filter in audacity did not remove the content below it.

I don't know how you chose this cut off frequency. Changing this cutoff frequency to 12kHz restored the content. (17kHz, 16kHz, 13 kHz removed it)

Please note : I also tried to upgrade pedal board from 0.6.1 to the latest 0.7.1 without change.

If you have some time to tell me how you selected 17kHz I could understand why it worked for you and not for me :wink: !
