### ISSUE TITLE
Why does the resulting finetuned voice differ depending on the training method ?

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#122]
Hi,

To correct a [pronunciation mistake](https://github.com/DigitalPhonetics/IMS-Toucan/issues/109#issuecomment-1476393538) I decided to retrain the Meta model. 

First I did not pay attention and only finetuned it with siwis dataset for 100k steps (phase 1 only). Then I finetuned this new model {Meta; Siwi} again with a reduced dataset (45 min long) for 10k and the voice was very similar to the target voice but there were still some small mistakes. 

So I wanted to see if I could improve it even more. So I trained from scratch a new model with {siwis ; and a tts generated dataset made with high quality neural voices}. So I trained for 100k of phase 1 but I did not pass phase 2 steps to eventually it trained up to 107 k steps (100k of phase 1 and 7 k of phase 2).

The I fine tuned this new model trained from scratch with my reduced dataset (45 min long) but after 10k the fine tuned model did not produce the same result. The voice has too high a pitch.

Why is it so ? Is it because I trained for 7 k of phase 2 and I would get the same high quality if I strictly trained without any step of phase 2 (so I have to retrain a last time) ? Or is it because there are overall only 7 different speakers in my datasets (compared to Meta) ? Or is it exactly because I did not train enough in phase 2 ?

Thanks in advance for your advice

**Comment by Flux9665** [comment]
This sounds very complicated. There will be a new release in the next few days, maybe it's better to start over with this new model. I don't know where the problem is or what caused it in this complicated setup.

**Comment by Ca-ressemble-a-du-fake** [comment]
Yeah that's complicated😄 ! I was frustrated not to be able to get again the quality I got once. But I am old enough to live with frustration😄. I will try the new release and see what I get ! Thanks anyway for answering all my questions with details. I will reply later.

**Comment by Ca-ressemble-a-du-fake** [comment]
Now I have the big picture of what happened. I write it in case it can help. I was using version 2.4 (which did not pronounce "sein, dessin, chemin" correctly see https://github.com/DigitalPhonetics/IMS-Toucan/issues/109) and then applied a git clone on the default branch after a fix was made. But there were also many other changes so it caused a mess. Now that I pasted the changes manually to the specific files it works.

I will push the version that works great in French on my repo so that people can use it if they need to.
