### ISSUE TITLE
Use of Toucan picture

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#123]
Hi,

I am starting a [blog post on IMS-Toucan](https://ca-ressemble-a-du-fake.github.io/clonage-voix-toucan/). It's just a guide on how to use it simply written in French, because otherwise everything is in English. 

I used your [Toucan Image](https://github.com/DigitalPhonetics/IMS-Toucan/blob/ImprovedControllableMultilingual/Utility/toucan.png) as post image because it was perfect to illustrate a guide on Toucan TTS! Is it fine that I reuse it (I tried to put a direct link but this does not seem to be allowed in Jekyll blog post front-matter) ?

 Regards

**Comment by Flux9665** [comment]
Sure, feel free to use it. 

On the topic of French: There is currently a challenge on French TTS going on, for which we are preparing a contribution. So in the near future, we will have a version of our system that is optimized specifically for French. Monday the third of April is the deadline for Challenge submissions, so then I'll compile a release that summarizes our system.

https://www.synsig.org/index.php/Blizzard_Challenge_2023

**Comment by Ca-ressemble-a-du-fake** [comment]
Thanks for the news, I'll keep an eye on this repo then! Good luck for the challenge :1st_place_medal: !
