### ISSUE TITLE
Is it possible to release Avocodo 48000 sample rate checkpoint

### ISSUE THREAD

**Issue by bharaniyv** [DigitalPhonetics/IMS-Toucan#124]
The newly released Avocodo 24000hz model is good but the output sounds little different than expected when finetuned on generated mels, I tried same finetuning on 48000 model too but due to lack of discriminator checkpoint it is taking too long to train. If you can release an Avocodo 48000 checkpoint, I think it will perform close to best full band TTS models after good finetuning.

Thanks

**Comment by Flux9665** [comment]
I attached a full 48kHz checkpoint to release 2.3

**Comment by bharaniyv** [comment]
Thanks for the model release
