### ISSUE TITLE
Why is build_all_aligner_dataset_caches called during training from scratch and not while fine tuning ?

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#126]
Hi,

What's the use of not calling `build_all_aligner_dataset_caches` during fine tuning if the dataset has never been seen before ? Should I run it beforehand ?

Thanks in advance for your answer :smiley:

**Comment by Flux9665** [comment]
No, this should never be called. It will be removed in the next version, it was just an experiment with multiprocessing. When a dataset is not found during loading, it is automatically created, no need to run anything manually.

**Comment by Ca-ressemble-a-du-fake** [comment]
Ok thanks for the clarification !
