### ISSUE TITLE
Emotional Voice

### ISSUE THREAD

**Issue by Simbaprince** [DigitalPhonetics/IMS-Toucan#140]
How to get correct value of parameters of IMS_toucan for several emotional voices such as angry, sad, excited, cheerful, shouting, whispering, terrified, friendly, unfriendly, hopeful, normal.

**Comment by Flux9665** [comment]
Some of the things you mention are not necessarily emotions, but you can achieve different speaking styles by providing a reference audio of that style and speaker to the `set_utterance_embedding` method of the inference interface.

**Comment by elitehacker0802** [comment]
There are several version and models are different.
Which version's generated voice is like human?

**Comment by Flux9665** [comment]
Versions are cumulative, so the most recent version has the best quality yet.
