### ISSUE TITLE
For info ThisSpeakerDoesNotExist UI on HuggingFace doesn't load

### ISSUE THREAD

**Issue by tomschelsen** [DigitalPhonetics/IMS-Toucan#146]
Displays a HuggingFace logo, says "Preparing Space" and a spinner, and stays there forever.

Other Flux9665 spaces UIs load correctly, so it doesn't come from my browser / machine / etc..

Have a nice day

**Comment by Flux9665** [comment]
Thanks for letting me know, I have no clue why the space did that, but simply restarting it seems to work. The logs did not show any reason for it being stuck.
