### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by michael-conrad** [DigitalPhonetics/IMS-Toucan#15]
I am getting an index error after several rounds of training a new model. 

Any suggestions?

Prepared a FastSpeech dataset with 2756 datapoints in Corpora/chr-w.
Training model
Reloading checkpoint_126775.pt
  0%|                                                                                                                     | 0/275 [00:00<?, ?it/s]
```python
/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/torch/optim/lr_scheduler.py:129: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  warnings.warn("Detected call of `lr_scheduler.step()` before `optimizer.step()`. "
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 275/275 [00:29<00:00,  9.26it/s]
Traceback (most recent call last):
  File "run_training_pipeline.py", line 78, in <module>
    pipeline_dict[args.pipeline](gpu_id=args.gpu_id,
  File "/home/muksihs/git/IMS-Toucan/TrainingInterfaces/TrainingPipelines/FastSpeech2_Cherokee_West.py", line 45, in run
    train_loop(net=model,
  File "/home/muksihs/git/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/fastspeech2_train_loop.py", line 195, in train_loop
    plot_progress_spec(net, device, save_dir=save_directory, step=step_counter, lang=lang, default_emb=default_embedding)
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/muksihs/git/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/fastspeech2_train_loop.py", line 57, in plot_progress_spec
    lbd.specshow(spec,
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/librosa/display.py", line 959, in specshow
    kwargs.setdefault("cmap", cmap(data))
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/librosa/display.py", line 576, in cmap
    min_val, max_val = np.percentile(data, [min_p, max_p])
  File "<__array_function__ internals>", line 5, in percentile
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3818, in percentile
    return _quantile_unchecked(
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3937, in _quantile_unchecked
    r, k = _ureduce(a, func=_quantile_ureduce_func, q=q, axis=axis, out=out,
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3515, in _ureduce
    r = func(a, **kwargs)
  File "/home/muksihs/miniconda3/envs/toucan_conda_venv/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4050, in _quantile_ureduce_func
    n = np.isnan(ap[-1])
IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by Flux9665** [comment]
It looks like you get some values in your spectrogram, which the spectrogram plotting function cannot handle. Maybe negative values? I'm not sure how that's possible. Maybe the model somehow became unstable during training and the loss escalated and caused values which are normally impossible in a spectrogram.

I had a look at your fork. The way you handle the tones and lenghtening characters as additional feature dimensions is reasonable. Probably not optimal to treat them as pseudo-phonemes, but it could definitely work. If you want to train a model only in Cherokee without pretraining in other languages, I recommend you instanciate the model as FastSpeech2(lang_embs=None). And if your data is only spoken by a single speaker, FastSpeech2(lang_embs=None, utt_embed_dim=None). Otherwise the language embedding and speaker embeddings are constant and you'd think then the model can just learn to ignore them, but for some reason, it confuses the model. 

I'm not sure if this error is caused by a bug, or if it's just deep learning being weird and the model suddenly diverged and produces impossible values. I don't see an obvious bug anyway.

**Comment by Flux9665** [comment]
2 things you can check: 

- The shape of the spectrogram that is produced in the progress plot function should not have a batch axis. If for some reson it has one, just .squeeze() the spectrogram tensor.
- If that's not it, check the range of values in the spectrogram. Are there NaN values or negative values in the spectrogram? If so, the model went crazy. In that case, retrain without the language embeddings if you only train on a single language. Maybe that keeps the model more stable.

**Comment by michael-conrad** [comment]
Right now I'm having issues recreating the venv.

The environment setup instructions have a command to install 1.9.0 but the
requirements file has 1.10 ?

I trying at the moment to get all the needed packages mostly installed via
conda, then will try and fill in missing ones with pip.

I was starting to get symbols not found and other weirdness when trying to
do a straight setup.

**Comment by michael-conrad** [comment]
Could I get you to run in your production copy?

```bash
conda activate toucan_conda_venv
conda env export --no-builds | grep -v "prefix:" > environment.yml
```

and post the resulting environment.yml to this issue ticket?

I noticed a warning about 1.9 vs 1.10 in the output so I'm trying to recreate a matching environment. Before trying to run it again to see if it would run all the way through.

As an aside, how much retraining does the aligner need for the added feature vectors? It didn't seem to fine tune for very long.

**Comment by Flux9665** [comment]
sure, github didn't allow me to upload with the yml suffix, so I made it a txt.

[environment.txt](https://github.com/DigitalPhonetics/IMS-Toucan/files/8458098/environment.txt)

The aligner finetunes for 5 epochs on new data. But since the symbols you added are non-segmental, it's probalby better to not finetune at all or at least finetune very little, so that the model doesn't unlearn how phonemes normally work. Actual training is mostly needed when you add genuine new phonemes.

**Comment by michael-conrad** [comment]
Hrm... no package "python-graphviz" available via pip.... I think it has been renamed to just "graphviz".

I also ended up having to install torch stuff via conda as the cu113 version isn't available for me via pip?

Here is my resulting environment. 

Now testing via ```python run_training_pipeline.py --gpu_id 0 chr```

[environment.txt](https://github.com/DigitalPhonetics/IMS-Toucan/files/8458144/environment.txt)

```yml
name: toucan_conda_venv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.9.30
  - cairo=1.16.0
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - expat=2.4.4
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gettext=0.19.8.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.14
  - graphviz=2.42.3
  - harfbuzz=2.4.0
  - icu=58.2
  - intel-openmp=2022.0.1
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libuv=1.42.0
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.2.0
  - ncurses=6.2
  - nettle=3.6
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pango=1.42.4
  - pcre=8.45
  - pip=21.0.1
  - pixman=0.40.0
  - python=3.8.11
  - python_abi=3.8
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - wheel=0.37.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - argparse==1.4.0
    - attrs==21.2.0
    - audioread==2.1.9
    - auraloss==0.2.1
    - cffi==1.14.6
    - charset-normalizer==2.0.4
    - clean-text==0.5.0
    - clldutils==3.9.0
    - colorama==0.4.4
    - colorlog==6.4.1
    - commonmark==0.9.1
    - csvw==1.11.0
    - cycler==0.10.0
    - cython==0.29.24
    - decorator==5.0.9
    - editdistance==0.5.3
    - emoji==1.4.2
    - ftfy==6.0.3
    - future==0.18.2
    - huggingface-hub==0.0.16
    - hyperpyyaml==1.0.0
    - idna==3.2
    - isodate==0.6.0
    - jiwer==2.3.0
    - joblib==1.0.1
    - kiwisolver==1.3.2
    - librosa==0.8.1
    - llvmlite==0.37.0
    - matplotlib==3.4.3
    - munkres==1.1.4
    - noisereduce==2.0.0
    - numba==0.54.0
    - numpy==1.20.3
    - packaging==21.0
    - panphon==0.19
    - phonemizer==2.2.2
    - pillow==8.3.2
    - pooch==1.5.1
    - pycparser==2.20
    - pygments==2.10.0
    - pyloudnorm==0.1.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - python-graphviz==0.17
    - python-levenshtein==0.12.2
    - pyworld==0.3.0
    - pyyaml==5.4.1
    - regex==2021.8.28
    - requests==2.26.0
    - resampy==0.2.2
    - rfc3986==1.5.0
    - rich==9.10.0
    - ruamel-yaml==0.17.16
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - segments==2.2.0
    - sentencepiece==0.1.96
    - sounddevice==0.4.2
    - soundfile==0.10.3.post1
    - speechbrain==0.5.10
    - tabulate==0.8.9
    - threadpoolctl==2.2.0
    - torch-complex==0.2.1
    - torchviz==0.0.2
    - tqdm==4.62.2
    - typing-extensions==3.10.0.2
    - unicodecsv==0.14.1
    - unidecode==1.2.0
    - unsilence==1.0.8
    - urllib3==1.26.6
    - wcwidth==0.2.5

```

**Comment by michael-conrad** [comment]
```python
UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
```

**Comment by michael-conrad** [comment]
I think I have it solved. Loss went to NaN. Have dropped the learning to rate to .0005.

**Comment by ssolito** [comment]
Hi, I guess I am having a similar issue. 
The model is training and also already saved a checkpoint in my model directory. But this error occurs:
Traceback (most recent call last):
  File "run_training_pipeline.py", line 66, in <module>
    pipeline_dict[args.pipeline](gpu_id=args.gpu_id,
  File "/home/aholab/sarah/IMS-Toucan/TrainingInterfaces/TrainingPipelines/FastSpeech2_finetune_to_Basque_Aintzane.py", line 42, in run
    train_loop(net=model,
  File "/home/aholab/sarah/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/fastspeech2_train_loop.py", line 203, in train_loop
    plot_progress_spec(net, device, save_dir=save_directory, step=step_counter, lang=lang, default_emb=default_embedding)
  File "/home/aholab/sarah/toucan_conda_venv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/aholab/sarah/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/fastspeech2_train_loop.py", line 55, in plot_progress_spec
    phoneme_vector = tf.string_to_tensor(sentence).squeeze(0).to(device)
  File "/home/aholab/sarah/IMS-Toucan/Preprocessing/TextFrontend.py", line 165, in string_to_tensor
    phones = self.get_phone_string(text=text, include_eos_symbol=True, for_feature_extraction=True)
  File "/home/aholab/sarah/IMS-Toucan/Preprocessing/TextFrontend.py", line 245, in get_phone_string
    phones = self.phonemizer_backend.phonemize([utt], strip=True)[0]
IndexError: list index out of range

Could be a temporary solution to comment the plot progress from fastspeech2_trainloop and just keep training?
May you help me?
[Aintzane_eusk.txt](https://github.com/DigitalPhonetics/IMS-Toucan/files/9997325/Aintzane_eusk.txt)

**Comment by Flux9665** [comment]
What is the utterance you have set in the plot_progress_spec for the language you are finetuning? It seems that the phonemizer does not output anything for your testing utterance. Is it maybe the default, which is an empty string?

If everything else works, then yes you can just remove the progress plotting, it is just there for convenience, not required.
