### ISSUE TITLE
Prosody Cloning Code

### ISSUE THREAD

**Issue by satani99** [DigitalPhonetics/IMS-Toucan#154]
Can anyone pls provide prosody cloning code to generate examples like this, https://toucanprosodycloningdemo.github.io/ ?

**Comment by Flux9665** [comment]
Here is the example script from the top level of the toolkit:

https://github.com/DigitalPhonetics/IMS-Toucan/blob/b4991d48fc3f6f576f8c937cc117e1cdd923ad55/run_prosody_override.py

**Comment by satani99** [comment]
Thank you
