### ISSUE TITLE
[Question] Code related to "EXACT PROSODY CLONING IN ZERO-SHOT MULTISPEAKER TEXT-TO-SPEECH"

### ISSUE THREAD

**Issue by leekwoon** [DigitalPhonetics/IMS-Toucan#161]
Thanks for the amazing work!

Can anyone guide me to  the specific parts of the repository where I can examine the code relevant to the paper(EXACT PROSODY CLONING IN ZERO-SHOT MULTISPEAKER TEXT-TO-SPEECH) methodology.

Specifically, I am looking for:
1. parts where duration, pitch, and energy are extracted (by using aligner).
2. parts where ASR (Automatic Speech Recognition) is utilized to compute the Phone-Error-Rate. for example:
![image](https://github.com/DigitalPhonetics/IMS-Toucan/assets/14149631/f0578bea-1dcd-4875-ac3d-92eb509f2b68)
3. way to plot following pitch curve figure
![image](https://github.com/DigitalPhonetics/IMS-Toucan/assets/14149631/7480ba77-f286-4270-a8bf-4225ac891d14)

**Comment by Flux9665** [comment]
Unfortunately I can only help you with one of those three points: 

1: The code where duration, pitch and energy are extracted is here: https://github.com/DigitalPhonetics/IMS-Toucan/blob/fc1c940012e21bbc18e194c1b4c43ceb6c1b7caf/InferenceInterfaces/UtteranceCloner.py#L46

2: The code to get the PER is not part of this repository. To get the PER of the ASR, we used the following tool:  https://github.com/DigitalPhonetics/IMS-Speech

3. I don't think I have the script to make this graphic anymore, it was written just for this paper without any general purpose. It is just plotting the spectrogram with librosa's specshow function and then plotting the output of the parselmouth pitch extraction function on the coresponding audio on top of the spectrogram.

Hope that helps!

**Comment by leekwoon** [comment]
I got it, thanks for your explanation!

**Comment by leekwoon** [comment]
I got it, thanks for your explanation!

> Unfortunately I can only help you with one of those three points:
> 
> 1: The code where duration, pitch and energy are extracted is here:
> 
> https://github.com/DigitalPhonetics/IMS-Toucan/blob/fc1c940012e21bbc18e194c1b4c43ceb6c1b7caf/InferenceInterfaces/UtteranceCloner.py#L46
> 
> 2: The code to get the PER is not part of this repository. To get the PER of the ASR, we used the following tool: https://github.com/DigitalPhonetics/IMS-Speech
> 
>     3. I don't think I have the script to make this graphic anymore, it was written just for this paper without any general purpose. It is just plotting the spectrogram with librosa's specshow function and then plotting the output of the parselmouth pitch extraction function on the coresponding audio on top of the spectrogram.
> 
> 
> Hope that helps!

I got it, thanks for your explanation!
