### ISSUE TITLE
Error when trying to run an example with Kyrgyz

### ISSUE THREAD

**Issue by jumasheff** [DigitalPhonetics/IMS-Toucan#173]
Alas, I didn't have a change to roll this locally and see logs.
I tried to run shorter examples as well. For example: `Салам досум, кандайсың?`.

Text of the example I tried to run with: `Санап көрсөң, жакшы эле болуп жатабы?`
See the screenshot:
<img width="1252" alt="Screenshot 2024-06-20 at 11 35 53" src="https://github.com/DigitalPhonetics/IMS-Toucan/assets/3319967/980afe54-3c83-4880-97d5-daaae3474a8c">

**Comment by Flux9665** [comment]
Thanks for letting me know! The phonemizer seems to produce extra symbols, which causes an error in the labels of the figure. I'll try to do a quick fix today and make a better fix (i. e. actually supporting those symbols) in the next version, that I'm planning to release in one or two weeks.

**Comment by Flux9665** [comment]
I pushed the update, the demo should no longer produce an error for this input. It will probably not sound very good, because the model doesn't know some of the phoneme modifiers, but hopefully once I finish the next version with improved support for many languages, it will sound better.
