### ISSUE TITLE
unable to do voice cloning with arabic

### ISSUE THREAD

**Issue by uni-saurabh-vyas** [DigitalPhonetics/IMS-Toucan#179]
Error:
```
*** TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not NoneType
```

code:
```
lang="ara"
tts = ToucanTTSInterface(device="cuda" if torch.cuda.is_available() else "cpu", tts_model_path="Meta", language=lang)

input_text = "<something in arabic script>"

# Loop through the speaker reference audio files in the folder
speaker_reference_folder = "/mnt/efs/saurabh/saurabh/tools/xtts/src_speakers_hindi3"
#dst_dir="/mnt/efs/jeena/to_saurabh/Hindi_phrases_sents/data/ims/test"

for file_name in os.listdir(speaker_reference_folder):
    if file_name.endswith('.wav'):
        speaker_reference = os.path.join(speaker_reference_folder, file_name)

        print(speaker_reference)

        # Set the speaker embedding to clone the voice
        tts.set_utterance_embedding(speaker_reference)

        # Synthesize speech with the cloned voice
        output_file_name = f"{dst_dir}/cloned_voice.wav"

        tts.read_to_file(text_list=[input_text], file_location=output_file_name)

del tts
```
It works for english and hindi, but for arabic it throws above error. Any thoughts?
I verified nothing wrong with audio file or input text

**Comment by Flux9665** [comment]
"ara" is not a valid language ID, it doesn't exist. The ISO code for standard Arabic is "arb"

**Comment by uni-saurabh-vyas** [comment]
Thanks, my bad. Now it's generating the audio, but getting the following warning (I hope its not a major problem)
'str' object has no attribute 'removeprefix'

**Comment by Flux9665** [comment]
I have never encountered the warning, but as long as it's generating audio, it should be fine. Arabic is among the languages where we had no training data, there might be improvements in the upcoming version (released hopefully this week)

**Comment by JettScythe** [comment]
@Flux9665 ara is the inclusive ISO639-3 code for Arabic
![image](https://github.com/user-attachments/assets/9f1b3515-262f-4852-bd07-ea18b6a1dae5)
and what is commonly returned when working with other python librares 
![image](https://github.com/user-attachments/assets/0b61f97a-c93d-437a-834a-3afc5a79973c)
