### ISSUE TITLE
Question Regarding Device Specs

### ISSUE THREAD

**Issue by canonhead** [DigitalPhonetics/IMS-Toucan#181]
Hello,

While attempting to run the demo scripts I keep getting a Segmentation Fault. The cluster I'm running on needs me to specify how much memory and how many CPU's I need, so I wanted to ask the ideal device specs for running these scripts.

**Comment by Flux9665** [comment]
I don't know which device specs are _ideal_, but I have an old laptop with 4GB of RAM and 4 CPU cores and it runs perfectly fine on it. I'm not sure if the segmentation fault is due to the compute requirements, or some installation problem.
