### ISSUE TITLE
Nancy availability?

### ISSUE THREAD

**Issue by canonhead** [DigitalPhonetics/IMS-Toucan#184]
Hi,

Any plans to make a pretrained model for cloning prosody available? As is, the script run_prosody_override.py simply doesn't work.

**Comment by Flux9665** [comment]
This has nothing to do with the Nancy dataset, you can use any model for this. The model downloader script downloads a model with the ID "Meta", you can just select this. I'll change the default.

**Comment by Flux9665** [comment]
I fixed a shape mismatch in the prosody override, now everything should work, as long as you're using an existing model.
