### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by a779159990** [DigitalPhonetics/IMS-Toucan#185]
Hello, your job is great, but I found that some languages have a much faster reasoning speed than most languages during the reasoning process, such as Japanese. Is this problem normal?

**Comment by Flux9665** [comment]
Thank you! The reason for the speed difference between languages is in the preprocessing. The model does the same for all languages, but it requires transcriptions in the phonetic alphabet. For some languages it takes longer to convert the regular written form to the IPA form. For Japanese, we use PyKakasi to unify the different writing systems and then use Transphone to get IPA symbols. Transphone is a bit slow.

**Comment by a779159990** [comment]
I understand, thank you！
