### ISSUE TITLE
Finetune_example_simple doesn't work!!!

### ISSUE THREAD

**Issue by AlexSteveChungAlvarez** [DigitalPhonetics/IMS-Toucan#191]
In recipes/finetune_example_simple. When you use this script as base for finetuning on only 1 language, it only outputs "EPOCH COMPLETE" in the terminal as an infinite loop, but never actually trains.
![image](https://github.com/user-attachments/assets/3395538e-2692-4cda-a24d-160b49137ebf)
![image](https://github.com/user-attachments/assets/2ef656f9-a922-4f5d-8e4c-655dee0f6c9c)

Usually for finetuning I'm taking about 20 minutes in the same computer and with a lot more data. This was a test on a very little simple dataset.

**Comment by Flux9665** [comment]
It does work, I just tried it. You probably have fewer samples in your dataset than are required to build one batch. Reduce the batchsize until it's less than the amount of samples in your dataset.

**Comment by AlexSteveChungAlvarez** [comment]
They were 40 datapoints (english) and the batch size was by default 12.
I tried it before too on a larger dataset (spanish) and didn't work neither. In that moment I thought it was because of the device, since it didn't have many resources, but this time I tried on a good computer.

**Comment by Flux9665** [comment]
I will try again, maybe I was on a different branch while testing. I will update you soon

**Comment by Flux9665** [comment]
I made a fresh clone and ran a test dataset with 500 datapoints. It works with no problems. I cannot reproduce your problem, so I need more details.

**Comment by AlexSteveChungAlvarez** [comment]
So tried again and it runs now, but it seems to be degrading at some point:
step 3:
![image](https://github.com/user-attachments/assets/c5b3eef3-8260-45a1-9280-57bd9cb12da0)
step 375:
![image](https://github.com/user-attachments/assets/ccd06fcb-c69c-4746-8dd1-a3ec223942cb)

**Comment by AlexSteveChungAlvarez** [comment]
Should I let it run the 5k steps and see what it gives?

**Comment by Flux9665** [comment]
So there was no problem with the finetune_example_simple?

If you have only 40 datapoints then 5000 steps is too much. The more datapoints you have and the cleaner they are, the longer you can run.

**Comment by AlexSteveChungAlvarez** [comment]
I don't know what may have been the problem, but in previous runs only an infinite printed message loop appeared. Now it works. I will try stopping it before step 375 which is the first degraded spectrogram.

**Comment by AlexSteveChungAlvarez** [comment]
The audios are in high quality, though, so I don't know why the model gets worse instead of clearer or remain clear.
