### ISSUE TITLE
Which languages are supported? No relevant list found

### ISSUE THREAD

**Issue by redpintings** [DigitalPhonetics/IMS-Toucan#192]
Which languages are supported? No relevant list found

**Comment by redpintings** [comment]
Does it support Chinese？

**Comment by Flux9665** [comment]
All 7000+ spoken languages in the ISO 639-3 standard are supported. So yes, Chinese is supported. Use language code "cmn".

I will add a table to the readme to prevent any future confusion.

**Comment by Flux9665** [comment]
Added a link to a language list to the readme: 

https://github.com/DigitalPhonetics/IMS-Toucan/blob/feb573ca630823974e6ced22591ab41cdfb93674/Utility/language_list.md
