### ISSUE TITLE
This is scary. At step 8,000 I'm getting decent English and passable Cherokee!

### ISSUE THREAD

**Issue by michael-conrad** [DigitalPhonetics/IMS-Toucan#20]
This is via the run interactive script.

[IMS-Toucan-samples-step-8000.zip](https://github.com/DigitalPhonetics/IMS-Toucan/files/8501906/IMS-Toucan-samples-step-8000.zip)

**Comment by Flux9665** [comment]
Glad to hear that it's working on Cherokee! My hearing is untrained for tone, so I'm not sure how well the tone works, but I could definitely hear distinct phonemes, which is usually a sign that it is not going to fail, but instead keep improving. You can call the set_utterance_method of the InferenceInterface object and pass a path to a file from the cherokee training set. If you have little training data for a certain language, the quality can improve when you use a speaker from the training set of the language that you want to use. The quality of the speaker transfer across languages scales with the amount of data it has seen. The default speaker is the speaker of the first sample in the union of datasets that you train on. 
https://github.com/DigitalPhonetics/IMS-Toucan/blob/81075a6d3a1a048f6f02ccda87579c896337a4fb/InferenceInterfaces/InferenceFastSpeech2.py#L48
