### ISSUE TITLE
Question about duration, pitch, and energy tensor lists for read_to_file

### ISSUE THREAD

**Issue by michael-conrad** [DigitalPhonetics/IMS-Toucan#21]
I'm trying to specify manually a tensor list for duration for ```InferenceFastSpeech2#read_to_file``` but I'm not finding any clues in the source to tell me what exactly I'm supposed to specify. I know that [torch.tensor(0.5)] doesn't work.

Help.

**Comment by Flux9665** [comment]
This is meant for when you want to control the speed of every phoneme individually. You pass in a list of tensors, where every tensor corresponds to one utterance in the list of utterances. This tensor should contain the amount of spectrogram frames for every phoneme. You can use the aligner output to clone an utterance with this, see run_utterance_cloner.py for this. 

From your example I assume though that's not what you want, I assume you want to scale the speed of the entire utterance with a scalar, right? I'll put it on my list for things to add in the next version. There's no way to access it from the InferenceInterface object yet, but you can change the default value for alpha here: 

https://github.com/DigitalPhonetics/IMS-Toucan/blob/81075a6d3a1a048f6f02ccda87579c896337a4fb/InferenceInterfaces/InferenceArchitectures/InferenceFastSpeech2.py#L141

**Comment by michael-conrad** [comment]
Yes, that is correct, I'm trying to slow the speech down in a global way, Cherokee is generally spoken slower with longer pauses between words and more carefully than the other languages I am training against.

I'm thinking being able to shift global pitch and global energy might also be useful.

**Comment by Flux9665** [comment]
Makes sense, I put it on my list.

**Comment by Flux9665** [comment]
Scaling the durations as well as the variance of energy and pitch is included in today's release. I tried it out with pretty extreme values and it still seemed to work fine in the meta checkpoint. I recommend a pitch scaling factor of ~1.8 for tonal languages and a duration scaling factor of ~1.4 for languages that are spoken slowly.
