### ISSUE TITLE
[Questions] Different behavior between latest github (default branch) and hugging face version

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [DigitalPhonetics/IMS-Toucan#22]
First of all, many thanks for the toolkit. 

Though the underlying models for Fastspeech2 and HifiGAN seem to be the same i get complete different behavior with inference of German texts: The github version gives me an English female speakers voice (model = Meta, language = de) while the hugging face speaker results in a German male speaker (German text, accent and voice). 

My question is in which file i can fine tune this behavior?

**Comment by michael-conrad** [comment]
I have an example showing the use of selecting different voices at (https://github.com/CherokeeLanguage/IMS-Toucan).

Look in the file ```run_chr_demo.py```

-MConrad

**Comment by eqikkwkp25-cyber** [comment]
Perfect, thank you.

**Comment by eqikkwkp25-cyber** [comment]
Resolved by adding a line to run_interactive_demo.py
`tts.set_utterance_embedding('german.wav')`
which downloaded reference audio for later usage.
