### ISSUE TITLE
[Question] How to set accent parameter which is used on hugging face?

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [DigitalPhonetics/IMS-Toucan#23]
On hugging face the second parameter is 'Select the Accent of the Speaker'. How and in which file i can set this?

Thank you.

**Comment by Flux9665** [comment]
The accent of the speaker is controlled via the language ID. In the toolkit there's the set_language method of the InferenceInterface object. This method does both at once, changing the language of the text (updating the ´text2phone´ attribute) and the accent of the speaker (updating the ´lang_id´ attribute). In the huggingface demo, we change the two things indepentently, which is not in the toolkit's code yet, but just as easy to implement. I'll add it to my list of changes I want to make for the next version. Until then I hope you can find a way to split the two things up yourself.

https://github.com/DigitalPhonetics/IMS-Toucan/blob/81075a6d3a1a048f6f02ccda87579c896337a4fb/InferenceInterfaces/InferenceFastSpeech2.py#L59

**Comment by eqikkwkp25-cyber** [comment]
Thank you. Adding an additional parameter 'accent' solved my issue: 

```
def set_language(self, lang_id, accent):
        """
        The id parameter actually refers to the shorthand. This has become ambiguous with the introduction of the actual language IDs
        """
        self.text2phone = ArticulatoryCombinedTextFrontend(language=lang_id, add_silence_to_end=True)
        if self.use_lang_id:
            self.lang_id = get_language_id(accent).to(self.device)
        else:
            self.lang_id = None
```
