### ISSUE TITLE
Feature Request: FAQ Creation

### ISSUE THREAD

**Issue by michael-conrad** [DigitalPhonetics/IMS-Toucan#30]
Take various questions from the issues and put them together with answers as an F.A.Q. document.

**Comment by Flux9665** [comment]
There is an FAQ section a the bottom of the readme, but I see your point with more specific questions like your questions on overfitting etc. 

So far they have not been frequently asked, so I'll wait until I feel there's a greter demand for such a summary.

**Comment by michael-conrad** [comment]
FYI: Here is a link showing usage of IMS-Toucan to help with language preservation by the creation of teaching materials.

https://www.youtube.com/channel/UCEvcgGgrC47LwcLgqr01h7A

**Comment by Flux9665** [comment]
Wow, that's an impressive use for the tool! Great job and thanks for sharing! We will go further into the low-resource direction, also with some focus on language revitalization. I hope our tool can further help with such efforts for even more endangered languages in the future.
