### ISSUE TITLE
Feature request: Apple M1 Support / Docker build

### ISSUE THREAD

**Issue by CharlieMcVicker** [DigitalPhonetics/IMS-Toucan#36]
Howdy there,

I am working with Michael Conrad on the Cherokee TTS project and am on an ARM architecture. I would love to work with the Digital Phonetics team to either get a working set of dependencies for performant cross-platform development or an addition to the README with steps for installing on Apple Silicon.

If this feels like too narrow of a use case I would also work with you to get an IMS-Toucan Docker image built so that this tool can be used anywhere in the cloud (and, conveniently, via Rossetta 2 and docker desktop on Mac), without any local install.

If you are interested in helping with either of these things, please be in touch.

**Comment by Flux9665** [comment]
Hi! Unfortunately I have no idea how to optimize for apple silicon chips, neither do I have access to a Mac or even any device running MacOS.

I update the requirements from time to time and make sure that ```pip install -r requirements.txt``` is sufficient to get everything running on windows and most linux systems. There are very few dependencies, I try to keep everything self-contained. And I'm always looking to remove existing dependencies and replace them with self-contained solutions. The speaker embedding will soon be replaced with something built in-house, but for phonemizing, espeak-ng will probably remain as the most tricky dependency if it's not shipped by default with a system.

IMS-Toucan is somewhere between a toolkit, a framework and a library, but mostly leaning towards toolkit. So it is not meant as a standalone application, it's just my way to share my research in a somewhat practical format. The way we use it in other projects is that we take the components that we need for that project and integrate them in the other codebase. If you want to figure out installation instructions for Apple Silicon devices, I'll gladly add them to the readme though :)

**Comment by CharlieMcVicker** [comment]
Okay. I will take a look and see what I can figure out.

Thanks for the response!

**Comment by CharlieMcVicker** [comment]
The following Dockerfile builds and installs everything from `requirements.txt` for IMS-Toucan, though I haven't tested calling into the toolkit to ensure everything is linked properly (as I'm guessing running via Rosetta 2 even inference will be very slow), and for the reasons I mention below.

```Dockerfile
FROM python:3.8.13

# install deps for python packages
RUN apt update
RUN apt install -y make cmake gcc g++ gfortran

WORKDIR app/
# install python packages
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install torch==1.10.1+cu111 torchvision==0.11.2+cu111 torchaudio==0.10.1 -f https://download.pytorch.org/whl/torch_stable.html

COPY . .
```

Unfortunately, CherokeeLanguage/IMS-Toucan has diverged slightly and now uses conda, so I'm looking into a micromamba-based image for CherokeeLanguage/IMS-Toucan.

That said, I will leave the pip-based image here in case anyone starting a new project wants a working docker build.
