### ISSUE TITLE
How to add pause in the middle of sentence?

### ISSUE THREAD

**Issue by saibharani** [DigitalPhonetics/IMS-Toucan#39]
Is there a way to add pause in the middle of sentence during synthesis eg: "What are you doing? Where are you going?" can I add a little pause after "doing" during synthesis?

Thanks

**Comment by Flux9665** [comment]
Sorry for the late reply, was on vacation. Yes, we use ~ as the pause marker in the phoneme representation. You can force the phonemizer to put a pause symbol there by adding a - or a , in the text at the point you want the pause to be. 

The model will however still decide end-to-end how long this pause should be. If you want a pause of a specific length, you can manipulate the pause duration by overwriting the predicted duration of the pause with a number of spectrogram frames of your choice. There is no interface to do this on a high level, but it should be very easy to hack one in. Just figure out the index of the pause symbol and then overwrite the output of the duration predictor at this index.

**Comment by saibharani** [comment]
Thanks, I too planned on changing the duration of the pause in the low-level code. I am planning to add an extra parameter to edit the duration at a high level. I will let you know how it goes.

**Comment by saibharani** [comment]
That actually worked I added a , in the text where I want more pause and it improved the pause duration a bit and I also tried changing the duration of pause by indexing at the low level it worked too. But I am planning to train a new model with more duration layers and also pitch, energy layers.
