### ISSUE TITLE
How is Mel-loss calculated with super-resolution?

### ISSUE THREAD

**Issue by roedoejet** [DigitalPhonetics/IMS-Toucan#42]
Hey Florian - Aidan here. Nice to meet you at ACL and thanks again for this implementation. 

I had a question about the super-resolution implementation in your HiFiGAN vocoder - you state that the model now takes Mel Spectrograms from 16kHz audio and you've adapted the upsampling rates to triple the sampling rate of the output waveform to 48kHz. Is there a requirement that your data is 48kHz then? For example the LJ dataset is only 22.05kHz, so when you're calculating the loss between the Mel spectrogram of the predicted waveform (`y_g_hat_mel` in the original implementation) and the ground truth Mel spectrogram (`y_mel` in the original implementation), there will be a sampling rate mismatch (48kHz for the generated Mel Spectrogram and 22.05kHz for the ground truth). Did I misunderstand something, or does this model require 48 kHz data even if the Mel spectrogram is 16 kHz?

Thanks!

**Comment by Flux9665** [comment]
Hi Aidan! Very glad to 'meet' you online again :)

That's correct, we need the desired output sample rate (in our case 48kHz) in all of the samples. That is taken care of in the HiFiGAN dataset preparation. If a dataset is not in 48kHz already, it will be simply be upsampled using librosa for technical reasons, even though that causes it to be flawed gold data. Both the gold wave and the predicted wave are in 48kHz, the gold wave is downsampled to 16kHz to calculate the spectrogram that is the input to the model. And when comparing the two 48kHz waves, everything works as usual.

I'm btw right now experimenting with including the discriminators from Avocodo (https://arxiv.org/abs/2206.13404) into a new and improved vocoder with the same upsampling trick, training is running at the moment. It will be in the next release, but it's already fairly stable: https://github.com/DigitalPhonetics/IMS-Toucan/blob/1475e6805d87a536bd76f0dc6daeb655a3d0e0fe/TrainingInterfaces/Spectrogram_to_Wave/HiFiGAN/HiFiGAN.py#L645 Generator stays mostly the same except for two tiny projections added, so the trained model can be a drop in replacement with just two lines of code added in the inference interface of HiFiGAN.

**Comment by roedoejet** [comment]
Yes - great to be in touch. re upsampling:  understood, thanks for the clarification!

Super exciting about Avocado too, I'll keep my eyes out for it 👀 

take care
