### ISSUE TITLE
some question about speaker generation?

### ISSUE THREAD

**Issue by WhiteFu** [DigitalPhonetics/IMS-Toucan#47]
Great Job！I'm interested in timbre generation？ Do you have a more detailed description **(like a paper)** or t he tutorial of the updates for the following two tasks。
1. We now use a self-supervised embedding function based on GST, but with a special training procedure to allow for very rich speaker conditioning.
2. We trained a GAN to sample from this new embeddingspace. This allows us to speak in voices of speakers that do not exist. We also found a way to make the sampling process very controllable using intuitive sliders. Check out our newest demo on Huggingface to try it yourself!

**Comment by WhiteFu** [comment]
I saw part of the inference script about the gan. Could you provide more details on how to train and control the speaker embedding with gan？

**Comment by Flux9665** [comment]
We are submitting a paper on this to ICASSP 2023 today. If it gets accepted, we will put a preprint online, but we only find out in a few months.

The training code for the GAN will be added in a few days, we're still cleaning it up a bit. The control mechanism is the one described in https://arxiv.org/abs/2004.02546 

Basically we modify the latent representations in the early layers of the GAN according to principal component analysis to change properties in the resulting embedding.

**Comment by WhiteFu** [comment]
Thanks for your reply, I look forward to reading your paper in a few months。
