### ISSUE TITLE
ModuleNotFoundError: No module named 'df'

### ISSUE THREAD

**Issue by athenasaurav** [DigitalPhonetics/IMS-Toucan#49]
Hello Everyone,

I m facing this issue while trying to run `run_interactive_demo.py` or  `run_text_to_file_reader.py`

The following error is returned :
Traceback (most recent call last):
```
  File "run_text_to_file_reader.py", line 5, in <module>
    from InferenceInterfaces.FastSpeech2Interface import InferenceFastSpeech2
  File "/content/IMS-Toucan/InferenceInterfaces/FastSpeech2Interface.py", line 11, in <module>
    from df.enhance import enhance
ModuleNotFoundError: No module named 'df'
```

I have already downloaded the models using `run_model_downloader.py`

Also when I'm checking the directory structure, I cannot find any Module named `df`.

Please let me know if I m doing anything wrong. 

Thanks

**Comment by athenasaurav** [comment]
Hello Everyone,

I was able to solve this issue by adding the cuda version to torchaudio as well.

`pip install torch==1.10.0+cu111 torchvision==0.11.0+cu111 torchaudio==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by athenasaurav** [comment]
I was able to solve this by adding the cuda version to torchaudio as well and changing the torch version accordingly.

`pip install torch==1.12.0+cu102 torchvision==0.13.0+cu102 torchaudio==0.12.0+cu102 --extra-index-url https://download.pytorch.org/whl/cu102`

**Comment by Flux9665** [comment]
Hi! ```df``` is the shorthand for ```deepfilternet```, which is part of the requirements.txt.

So it should be there after running ```pip install -r requirements.txt```

It can be installed individually by running ```pip install deepfilternet```

I'm not sure how changing the torch installation fixed the missing requirement for you, but it's good to hear that it works now!
