### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by tq821ur** [DigitalPhonetics/IMS-Toucan#52]
Hello , where are the new samples which is generated by the new Vo-coder named Avocod, can you provide some please for me to hear (seen or unseen) , they claim it is Artifact-free.

**also, how many thousand steps/epochs did you train this new vocoder for / and can it be used as a pretrained model ?

Feel free to close the issue after responding.

Thanks in Advance.

**Comment by Flux9665** [comment]
I have trained the Avocodo Vocoder for 1.5 million steps so far, but I still continue the training. It can be used as pretrained model and it doesn't need to be finetuned, I don't notice a difference between seen and unseen speakers. This demo that I made uses the new vocoder together with a TTS, I don't have any samples with vocoded ground-truth speech available at the moment. 

https://huggingface.co/spaces/Flux9665/ThisSpeakerDoesNotExist

The model is in the release page of this repo, however I will update it soon with a newer version that has been trained for more steps. After 1.5 million, the improvements become very very small.

Even though they claim that it is artifact free, I still notice some artifacts. But overall I think there are less artifacts than with HiFiGAN. I'm still waiting on a denoising diffusion based vocoder that is equally fast and general with the same quality. I heard that diffusion based vocoders usually don't have these artifacts at all; just a little worse overall quality and they are of course computationally more expensive than the GAN based ones.
