### ISSUE TITLE
Sound quality dropped compared to Huggingface

### ISSUE THREAD

**Issue by lagleki** [DigitalPhonetics/IMS-Toucan#62]
The old version (without Avocodo, without full IPA support) somehow produces better results than the current one.
Hard to say where exactly the quality dropped.
Did anyone notice that? Any hints at finetuning the inference?

**Comment by Flux9665** [comment]
For the current version, we are trying out lots of things with the embedding function, that's a pretty major change. New models with an improved embedding function will come soon. Also, I'm not sure if the Avocodo model is actually better than the HiFiGAN model. In theory Avocodo adresses exactly the problems that HiFiGAN had, but the results are mixed. Maybe I need to spend some more time on the architecture.
