### ISSUE TITLE
About Multilingual Training 

### ISSUE THREAD

**Issue by GoArsenal** [DigitalPhonetics/IMS-Toucan#68]
Hi,
I want to train a cross-lingual (Chinese and English) model from scratch,  so I choose `pipeline=meta` in `run_training_pipeline.py`, and I got a warning at the beginning as follows:
```
"UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the      
learning rate schedule."
```
Then I check the train loop file (`IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/meta_train_loop.py`), but I didn't find any questions, does this warning affect the model result? 

BTW, [Silero VAD](https://github.com/snakers4/silero-vad/wiki/Examples-and-Dependencies#dependencies) seems need **pytorch >= 1.12.0**, but the suggestion is **torch==1.10.1** 😄 
Thanks!

**Comment by bharaniyv** [comment]
No as mentioned in the [FAQ](https://github.com/DigitalPhonetics/IMS-Toucan/#faq-) section of this repo, it is expected behaviour and it does not effect the output quality of your model.

**Comment by GoArsenal** [comment]
> No as mentioned in the [FAQ](https://github.com/DigitalPhonetics/IMS-Toucan/#faq-) section of this repo, it is expected behaviour and it does not effect the output quality of your model.

Thank you for your reply! I think I may be blind, sorry to waste your time 🤣

**Comment by Flux9665** [comment]
About the torch requirement for the silero VAD: Thank you for bringing this up, they updated their models recently and with that they probably also bumped up the pytorch version. The upcomming release of this toolkit will also overhaul the dependencies, so I'll take that into account.
