### ISSUE TITLE
Can you release Avocodo 24k vocoder model

### ISSUE THREAD

**Issue by bharaniyv** [DigitalPhonetics/IMS-Toucan#69]
Hi 
I trained an 24000 sample rate FastSpeech2 model, but I don't have a vocoder with me and Vocoders in ParallelWaveGAN repo are not performing as good as Avocodo model, Since you started training Avocodo 24k model, can you release it so that I can check the quality of my model?

Thanks

**Comment by Flux9665** [comment]
The current state is here: https://drive.google.com/file/d/1gH4OkxpSTmReMas6vFsv5Y-AgQQXeJ2N/view?usp=sharing

The feature matching loss is still increasing, that usually means it's still learning. Also it still takes 16kHz spectrograms as input. Just the output is 24kHz.

**Comment by bharaniyv** [comment]
Ok I thought it takes 24kHz spectrograms as input anyway thanks for the link I will give it a try.
