### ISSUE TITLE
Multi-Speaker Training

### ISSUE THREAD

**Issue by kin0303** [DigitalPhonetics/IMS-Toucan#71]
Hi, I want to do multi-speaker training. I have data for 4 speakers and one of the speakers has a very large data of approximately 20,000 audio files with a duration of time of 1-11 seconds while the other speakers only have approximately 1000 audio files. Should the speaker with 20,000 audio files be reduced so that the dataset used is balanced? And should I change the sample rate to 16,000? My Dataset sample rate is 44,100.

**Comment by bharaniyv** [comment]
The code can auto resample to 16000hz you just have to add dataset processing function in `path_to_transcript_dicts` file.

You don't have to limit the no of files, the model is capable of learning speaker characteristics from limited number of samples too, and if your language is not currently in the pre-trained languages list, it is much better if you use full data since it can help learn language better.

**Comment by kin0303** [comment]
Inside TextFrouted.py I added:
```
         elif language == "id":
             self.g2p_lang = "id"
             self. expand_abbreviations = lambda x: x
             if not silent:
                 print("Created an Indonesian Text-Frontend")
```

Because I will conduct training using Indonesian

And in path_to_transcript_dicts.py I added:
```
def build_path_to_transcript_dict_Tendy():
     root = "/IMS-Toucan/Tendy"
     path_to_transcript = dict()
     with open(os.path.join(root, "metadata.csv"), "r", encoding="utf8") as file:
         lookup = file.read()
     for line in lookup.split("\n"):
         if line.strip() != "":
             norm_transcript = line.split("|")[2]
             wav_path = os.path.join(root, "wav", line.split("|")[0] + ".wav")
             if os.path.exists(wav_path):
                 path_to_transcript[wav_path] = norm_transcript
     return limit_to_n(path_to_transcript)

def build_path_to_transcript_dict_Barlin():
     root = "/IMS-Toucan/Barlin"
     path_to_transcript = dict()
     with open(os.path.join(root, "metadata.csv"), "r", encoding="utf8") as file:
         lookup = file.read()
     for line in lookup.split("\n"):
         if line.strip() != "":
             norm_transcript = line.split("|")[2]
             wav_path = os.path.join(root, "wav", line.split("|")[0] + ".wav")
             if os.path.exists(wav_path):
                 path_to_transcript[wav_path] = norm_transcript
     return limit_to_n(path_to_transcript)

def build_path_to_transcript_dict_Nilda():
     root = "/IMS-Toucan/Nilda"
     path_to_transcript = dict()
     with open(os.path.join(root, "metadata.csv"), "r", encoding="utf8") as file:
         lookup = file.read()
     for line in lookup.split("\n"):
         if line.strip() != "":
             norm_transcript = line.split("|")[2]
             wav_path = os.path.join(root, "wav", line.split("|")[0] + ".wav")
             if os.path.exists(wav_path):
                 path_to_transcript[wav_path] = norm_transcript
     return limit_to_n(path_to_transcript)

def build_path_to_transcript_dict_Elsa():
     root = "/IMS-Toucan/Elsa"
     path_to_transcript = dict()
     with open(os.path.join(root, "metadata.csv"), "r", encoding="utf8") as file:
         lookup = file.read()
     for line in lookup.split("\n"):
         if line.strip() != "":
             norm_transcript = line.split("|")[2]
             wav_path = os.path.join(root, "wav", line.split("|")[0] + ".wav")
             if os.path.exists(wav_path):
                 path_to_transcript[wav_path] = norm_transcript
     return limit_to_n(path_to_transcript)
```
Is it correct like this?

**Comment by kin0303** [comment]
I try to train using:
 ```
python TrainingInterfaces/TrainingPipelines/FastSpeech2_finetuning_example.py --resume_checkpoint IMS-Toucan/Models/FastSpeech2_Meta --finetune
```

and got some error like this:
```
Traceback (most recent call last):
  File "/IMS-Toucan/IMS-Toucan/TrainingInterfaces/TrainingPipelines/FastSpeech2_finetuning_example.py", line 8, in <module>
    from TrainingInterfaces.Text_to_Spectrogram.FastSpeech2.FastSpeech2 import FastSpeech2
ModuleNotFoundError: No module named 'TrainingInterfaces'
```

**Comment by bharaniyv** [comment]
In the TextFrontend.py file you should also add your new language to the get_language_id function by giving it a new language ID.

As per the 2nd issue, I think your directory structure is wrong, I can see two IMS-Toucan folders in the traceback and you are probably trying to execute from the outermost IMS-Toucan folder which leads to the No module found error, Instead you should clean your directory structure to have only one IMS-Toucan folder and all the sub folders including Models folder should be there in IMS-Toucan folder and you should execute the code from there which will solve the issue

**Comment by kin0303** [comment]
> In the TextFrontend.py file you should also add your new language to the get_language_id function by giving it a new language ID.

Yeah, I've done with that

> As per the 2nd issue, I think your directory structure is wrong, I can see two IMS-Toucan folders in the traceback and you are probably trying to execute from the outermost IMS-Toucan folder which leads to the No module found error, Instead you should clean your directory structure to have only one IMS-Toucan folder and all the sub folders including Models folder should be there in IMS-Toucan folder and you should execute the code from there which will solve the issue

I've renamed my directory, but still get the issue

```
(ims_env) H310M-H-2-0:Toucan/IMS-Toucan$ python3 TrainingInterfaces/TrainingPipelines/FastSpeech2_finetuning_example.py --resume_checkpoint Models/FastSpeech2_Meta --finetune
Traceback (most recent call last):
  File "TrainingInterfaces/TrainingPipelines/FastSpeech2_finetuning_example.py", line 8, in <module>
    from TrainingInterfaces.Text_to_Spectrogram.FastSpeech2.FastSpeech2 import FastSpeech2
ModuleNotFoundError: No module named 'TrainingInterfaces'
```

**Comment by kin0303** [comment]
During training using:
```
python 3 FastSpeech2_finetuning_example.py --resume checkpoint Models/FastSpeech2_Meta --finetuning 
```
and will be immediately resampled, is it true?

**Comment by bharaniyv** [comment]
No you shouldn't run the FastSpeech2 training file directly instead you should run `python3 run_training_pipeline.py NAME_OF_YOUR_TRAINING --gpu_id 0 --resume checkpoint Models/FastSpeech2_Meta --finetune`

and remember to add your training example to the run_training_pipeline.py as mentioned in the README.md file [here](https://github.com/DigitalPhonetics/IMS-Toucan#training-a-model-)

**Comment by kin0303** [comment]
> No you shouldn't run the FastSpeech2 training file directly instead you should run `python3 run_training_pipeline.py NAME_OF_YOUR_TRAINING --gpu_id 0 --resume checkpoint Models/FastSpeech2_Meta --finetune`
> 
> and remember to add your training example to the run_training_pipeline.py as mentioned in the README.md file [here](https://github.com/DigitalPhonetics/IMS-Toucan#training-a-model-)

I'm sorry,  I don't get the point

**Comment by kin0303** [comment]
> No you shouldn't run the FastSpeech2 training file directly instead you should run `python3 run_training_pipeline.py NAME_OF_YOUR_TRAINING --gpu_id 0 --resume checkpoint Models/FastSpeech2_Meta --finetune`
> 
> and remember to add your training example to the run_training_pipeline.py as mentioned in the README.md file [here](https://github.com/DigitalPhonetics/IMS-Toucan#training-a-model-)

Thank you so much, now I'm trying to run ```python3 run_training_pipeline.py NAME_OF_YOUR_TRAINING --gpu_id 0 --resume checkpoint Models/FastSpeech2_Meta --finetune```. I'll update the progress later

**Comment by kin0303** [comment]
Hi @bharaniyv ,  I've a question about finetuning function that requires setting a language :

https://github.com/DigitalPhonetics/IMS-Toucan/blob/94d6a5798ee31a9db13254c822df6dfc32339731/TrainingInterfaces/TrainingPipelines/FastSpeech2_finetuning_example.py#L57

Can I set a language written like this:

```lang="id" and "en",  # CHANGE THIS TO THE LANGUAGE YOU'RE TRAINING ON```

**Comment by kin0303** [comment]
![Screenshot from 2022-12-28 13-37-47](https://user-images.githubusercontent.com/103550046/209769442-1c23d002-8687-4e28-96f8-2e800ca5391b.png)
Do you know why the spectrogram loss is nan?

Did it happen because of this?
```lang="id, en",  # CHANGE THIS TO THE LANGUAGE YOU'RE TRAINING ON```

**Comment by kin0303** [comment]
I try with one language, but got this errors:
```
Preparing
Prepared a FastSpeech dataset with 1019 datapoints in Corpora/Alex.
Prepared a FastSpeech dataset with 18833 datapoints in Corpora/Hanna.
Training model
/home/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py:554: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 6, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
100%|███████████████████████████████████████████| 4963/4963 [1:05:00<00:00,  1.27it/s]
Traceback (most recent call last):
  File "run_training_pipeline.py", line 77, in <module>
    pipeline_dict[args.pipeline](gpu_id=args.gpu_id,
  File "/media/7A76476176471D6F/Toucan/IMS-Toucan/TrainingInterfaces/TrainingPipelines/FastSpeech2_finetuning_example.py", line 54, in run
    train_loop(net=model,
  File "/media/7A76476176471D6F/Toucan/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/fastspeech2_train_loop.py", line 273, in train_loop
    path_to_most_recent_plot = plot_progress_spec(net,
  File "/home/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/7A76476176471D6F/Toucan/IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/FastSpeech2/fastspeech2_train_loop.py", line 71, in plot_progress_spec
    lbd.specshow(spec,
  File "/home/.local/lib/python3.8/site-packages/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/librosa/display.py", line 853, in specshow
    kwargs.setdefault("cmap", cmap(data))
  File "/home/.local/lib/python3.8/site-packages/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/librosa/display.py", line 603, in cmap
    min_val, max_val = np.percentile(data, [min_p, max_p])
  File "<__array_function__ internals>", line 180, in percentile
  File "/home/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4166, in percentile
    return _quantile_unchecked(
  File "/home/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4424, in _quantile_unchecked
    r, k = _ureduce(a,
  File "/home/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 3725, in _ureduce
    r = func(a, **kwargs)
  File "/home/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4593, in _quantile_ureduce_func
    result = _quantile(arr,
  File "/home/.local/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4699, in _quantile
    take(arr, indices=-1, axis=DATA_AXIS)
  File "<__array_function__ internals>", line 180, in take
  File "/home/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/home/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```

**Comment by bharaniyv** [comment]
No you can't use and statement if you want to finetune on multiple languages you can take reference from Meta file.

as per the nan in spectrogram loss, there are many reasons for that to happen like: Your dataset is not of good quality, Too small batch size, learning rate is not right for the given batch size, its better if you start experimenting with the above options and there is also a script in the meta example file that removes all possible nan datasamples you can give it a try too.

**Comment by kin0303** [comment]
> Too small batch size, learning rate is not right for the given batch size,

May be because of this, I'm using batch size : 4 and lr=0.0001 for this experiment and how to give the learning rate right for batch size, how to counting them?

**Comment by Flux9665** [comment]
Today's release brings new train loop helper functions, new architectures and new pretrained models, I hope this will fix the NaN issues.
