### ISSUE TITLE
Multi-Speaker Inference

### ISSUE THREAD

**Issue by kin0303** [DigitalPhonetics/IMS-Toucan#72]
How to select speakers on inference and how to show the list of speakers?

**Comment by tomschelsen** [comment]
It is exposed through the `voice_seed` argument of the `read` method of the `ControllableInterface` class, see : https://github.com/DigitalPhonetics/IMS-Toucan/blob/1c581e06b1cabf07c89568169cf4317aa50b9896/InferenceInterfaces/ControllableInterface.py#L44

See https://github.com/DigitalPhonetics/IMS-Toucan/blob/ControllableMultilingual/run_gradio_demo.py for an example usage of that class.

**Comment by kin0303** [comment]
> It is exposed through the `voice_seed` argument of the `read` method of the `ControllableInterface` class, see :
> 
> https://github.com/DigitalPhonetics/IMS-Toucan/blob/1c581e06b1cabf07c89568169cf4317aa50b9896/InferenceInterfaces/ControllableInterface.py#L44
> 
> See https://github.com/DigitalPhonetics/IMS-Toucan/blob/ControllableMultilingual/run_gradio_demo.py for an example usage of that class.

can you give me an example?

**Comment by kin0303** [comment]
I did training in 2 languages, each with 2 speakers: male and female. How do I make it so that during inference I can choose the speakers I will use? Because I only understand that to replace the speakers we can use the audio reference

**Comment by Flux9665** [comment]
There is no fixed list of speakers, there are theoretically infinite speakers possible. To change the voice, you first create a Inference Interface using a multispeaker model

https://github.com/DigitalPhonetics/IMS-Toucan/blob/1c581e06b1cabf07c89568169cf4317aa50b9896/InferenceInterfaces/FastSpeech2Interface.py#L23

and then call the set utterance embedding method on the interface

https://github.com/DigitalPhonetics/IMS-Toucan/blob/1c581e06b1cabf07c89568169cf4317aa50b9896/InferenceInterfaces/FastSpeech2Interface.py#L93

As argument it takes a filepath to a reference audio, which it will then load and extract an embedding. This embedding is then used as conditioning signal during inference. To change between the two speakers in your data, just call the set utterance embedding method and pass in one of the samples from the dataset from one of the speakers.

**Comment by kin0303** [comment]
> There is no fixed list of speakers, there are theoretically infinite speakers possible. To change the voice, you first create a Inference Interface using a multispeaker model
> 
> https://github.com/DigitalPhonetics/IMS-Toucan/blob/1c581e06b1cabf07c89568169cf4317aa50b9896/InferenceInterfaces/FastSpeech2Interface.py#L23
> 
> and then call the set utterance embedding method on the interface
> 
> https://github.com/DigitalPhonetics/IMS-Toucan/blob/1c581e06b1cabf07c89568169cf4317aa50b9896/InferenceInterfaces/FastSpeech2Interface.py#L93
> 
> As argument it takes a filepath to a reference audio, which it will then load and extract an embedding. This embedding is then used as conditioning signal during inference. To change between the two speakers in your data, just call the set utterance embedding method and pass in one of the samples from the dataset from one of the speakers.


Thank you for your reply. For this line how to use the ```language``` if I use multilingual models? 

https://github.com/DigitalPhonetics/IMS-Toucan/blob/1c581e06b1cabf07c89568169cf4317aa50b9896/InferenceInterfaces/FastSpeech2Interface.py#L25

**Comment by Flux9665** [comment]
You can either set the language when you create the inference interface object, but you can also change it later with the set_language method of the inference object:

https://github.com/DigitalPhonetics/IMS-Toucan/blob/1c581e06b1cabf07c89568169cf4317aa50b9896/InferenceInterfaces/FastSpeech2Interface.py#L108
