### ISSUE TITLE
RuntimeError: language "de" is not supported by the espeak backend

### ISSUE THREAD

**Issue by GoArsenal** [DigitalPhonetics/IMS-Toucan#75]
I try to train a new mulitilingual model, it contains three languages(english, german and spanish),  I got an error when trying to `prepare_fastspeech_corpus` for these three languages:
`RuntimeError: language "de" is not supported by the espeak backend`
but when i Individual run `$python Preprocessing/TextFrontend.py`, it works well ! 

My `phonemizer` version is :
`$phonemize --version ` 
`phonemizer-3.2.1`
`available backends: espeak-ng-1.51, segments-2.2.1`
`uninstalled backends: espeak-mbrola, festival`

My `FastSpeech2_MetaCheckpoint.py`:
```
    english_datasets = list()
    german_datasets = list()
    spanish_datasets = list()
   
    english_datasets.append(prepare_fastspeech_corpus(transcript_dict=build_path_to_transcript_dict_libritts(),
                                                      corpus_dir=os.path.join(PREPROCESSING_DIR,"libri_train_clean_100"), 
                                                      lang="en"))

    german_datasets.append(prepare_fastspeech_corpus(transcript_dict=build_path_to_transcript_dict_mailabs_de(),
                                                     corpus_dir=os.path.join(PREPROCESSING_DIR, "deu_mailabs"),
                                                     lang="de"))

    spanish_datasets.append(prepare_fastspeech_corpus(transcript_dict=build_path_to_transcript_dict_mailabs_esp(),
                                                      corpus_dir=os.path.join(PREPROCESSING_DIR, "esp_mailabs"),          
                                                      lang="es"))
```
My `build_path_to_transcript` function:
>PS:each line of the `wavs` file is the path of the audio and the `trans` file is the corresponding transcript 
```
def build_path_to_transcript_dict_mailabs_de():                                                                           
    root = f"IMS-Toucan/eng-deu-esp/deu"
    path_to_transcript = dict()
    with open(os.path.join(root, "trans"), "r", encoding="utf8") as f1: 
        text_lookup = f1.read().split("\n")
    with open(os.path.join(root, "wavs"), "r", encoding="utf8") as f2: 
        wav_lookup = f2.read().split("\n")
    for t, w in zip(text_lookup, wav_lookup):
        path_to_transcript[w] = t 

    return limit_to_n(path_to_transcript)
```

Can you give me some suggestions? Thank you very much!

**Comment by kin0303** [comment]
It seems you haven't added the language you are using in TextFrontend.py
https://github.com/DigitalPhonetics/IMS-Toucan/issues/45#issuecomment-1283163131

**Comment by Flux9665** [comment]
All of the languaghes you are using (en, de and es) are already included in the TextFrontend, so that should not be a problem.

Someone else has in the past reported that they got this error, even though it worked when they ran the tests in the text frontend on their own. But I never heard back from them again, so I'm not sure if they solved it or they gave up. Unfortunately I cannot reproduce the problem, so I cannot really help. I tried the versions that you specified and even used the mailabs data, but it worked for me under both Windows and Linux. It might be something strange like the order of the imports or so, because the phonemizer library is only an interface to espeak and does not actually carry out the functionality of espeak. So maybe there is a weird interaction between multiprocessing and espeak being executed in the background. If you find a solution, please let me know.

**Comment by GoArsenal** [comment]
> All of the languaghes you are using (en, de and es) are already included in the TextFrontend, so that should not be a problem.
> 
> Someone else has in the past reported that they got this error, even though it worked when they ran the tests in the text frontend on their own. But I never heard back from them again, so I'm not sure if they solved it or they gave up. Unfortunately I cannot reproduce the problem, so I cannot really help. I tried the versions that you specified and even used the mailabs data, but it worked for me under both Windows and Linux. It might be something strange like the order of the imports or so, because the phonemizer library is only an interface to espeak and does not actually carry out the functionality of espeak. So maybe there is a weird interaction between multiprocessing and espeak being executed in the background. If you find a solution, please let me know.

Thank you for your response. I discovered another person who had the same issue(https://github.com/espeak-ng/espeak-ng/issues/1580) and who fixed it by switching from Ubuntu to Windows 11. The problem persists despite my attempts to reinstall the espeak package and establish a fresh Python environment on my Linux system, therefore I want to do some experiments using the Google Colab. Once more, I appreciate your response.
