### ISSUE TITLE
Voice cloning results with released model

### ISSUE THREAD

**Issue by nathanmacauu** [DigitalPhonetics/IMS-Toucan#80]
Hi dev team,
I am trying to use your released model to test the results of your voice cloning feature.
However, the results are pretty bad at the end.
I am not sure if I am doing everything right, because there are no guideline to it, so the following are my steps:
1. first of all, download the models, and install the environment
2. run utterance_cloner.py, change path to model from calling LibriGST_new to Meta (the name of the downloaded model)
3. upload my own reference audio and rename as test.wav, noted that there are two cloner in the py script, one called clone_utterance, and one biblical_accurate_angel_mode, I don't know the difference between them. But I simply changed all wav files into my single wav file.
4. And the result are generated, but it is totally distorted, that it is not even close to the results from your demonstrating page.

Do I need to change any parameters/variables, that I was doing it wrong?
Or simply I have to fine tune the model before applying it?

And lastly, are there a community for discussion?
Thank you.

**Comment by Flux9665** [comment]
Hi! Sorry for taking so long to reply, I was sick for a long time. The utterance cloner script is meant for cloning the prosody of a specific utterance, not necessarily the voice. To just do voice cloning you don't need this. Instead you could use the `read_texts` function in `run_text_to_file_reader.py`.

https://github.com/DigitalPhonetics/IMS-Toucan/blob/f0c2d9e16b4b48289709c6fe0c6c71460238f093/run_text_to_file_reader.py#L8

For the speaker reference, you input the path to your reference speech.
