### ISSUE TITLE
How to improve the quality of the result?

### ISSUE THREAD

**Issue by kin0303** [DigitalPhonetics/IMS-Toucan#83]
I want to ask about audio inference. I did multispeaker training with each language having 2 speakers, namely female and male. Why is it that if I use my default speakers it gives better quality than I use the reference speakers? Even though the speaker reference that I use is a training dataset.

**Comment by Flux9665** [comment]
It usually comes down to the quality of the dataset. The model will learn to associate speaker embeddings from speakers with lower quality to lower quality outputs.

**Comment by kin0303** [comment]
> It usually comes down to the quality of the dataset. The model will learn to associate speaker embeddings from speakers with lower quality to lower quality outputs.

So what should be done so that the quality is as good as when using the default speaker?

**Comment by Flux9665** [comment]
There usually are not that many options if the quality of the data is not that good. How many datapoints do you have available? And are you already starting from a pretrained checkpoint trained on more speakers?

**Comment by Flux9665** [comment]
Today's release comes with a new architecture and new pretrained models, maybe they can help.
