### ISSUE TITLE
Input type and weight type should be the same

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#88]
Hi,

While running inference I keep getting `IMS-Toucan/TrainingInterfaces/Text_to_Spectrogram/PortaSpeech/Glow.py", line 123, in forward
    z = F.conv2d(x, weight)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same`

It is solved by running on CPU but it can also be solved more elegantly by bringing the model weight to the same device than the data (adding `.to(x.device)` on line 123 in forward method of Glow.py) :
`weight = weight.view(self.n_split, self.n_split, 1, 1).to(x.device)` 

Should I write a pull request or you want to correct it in a different way ?

**Comment by Flux9665** [comment]
good catch, thanks for letting me know. Feel free to make a PR, otherwise I'll fix it some time in the next few days.

**Comment by Ca-ressemble-a-du-fake** [comment]
Ok gonna do it.
