### ISSUE TITLE
Resuming training starts from 0 instead of the latest checkpoint

### ISSUE THREAD

**Issue by Ca-ressemble-a-du-fake** [DigitalPhonetics/IMS-Toucan#89]
Hi,

I gave "--resume" option a try and at the beginning it reads "Loading checkpoint XYZ" so it is OK. But then it starts from 0 again and does not write anything until it exceeds the previous checkpoint count.

I haven't had the chance to test the --resume_checkpoint option to see if it behaves the same way.

**Comment by Flux9665** [comment]
Strange, I cannot reproduce this. Are you sure you didn't accidentially set the --finetune flag, which will load the model but start from 0?

**Comment by Ca-ressemble-a-du-fake** [comment]
Gonna check and keep you posted. I tried the resume_checkpoint argument and it worked correctly. 

Edit :  the used command was `python3 run_training_pipeline.py fine_Alice --gpu_id 0 --resume --wandb 2>&1`

**Comment by Ca-ressemble-a-du-fake** [comment]
Now (version 2.5) that I try again it works as expected, resuming from the latest checkpoint. I see an incorrect ampersand in the command above, maybe this was the problem. The correct command is `python3 run_training_pipeline.py fine_Alice --gpu_id 0 --resume --wandb 2>1` and it works for me.
